### PR TITLE
Add additional location for /confirmdeletion

### PR DESCRIPTION
**Pull request by mrskizzex**
Adding location for /confirmdeletion for better compatibility with Authelia.

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by aptalca** [comment]
We don't want to bypass auth for deletion

**Comment by mrskizzex** [comment]
I made this suggestion after encountering errors with default setup.
Deleting one torrent in qBittorent works but two or more redirects to Authelia.

```
XX.XX.XX.XX - - [25/Jul/2021:15:16:42 +0200] "GET /confirmdeletion.html?hashes=2383b50f94801bf93d700228f0e13c13884853a1&deleteFiles=false HTTP/2.0" 200 791 "https://qbtvpn.example.com/"
```
Returns 200 and shows deletion confirmation

```
XX.XX.XX.XX - - [25/Jul/2021:15:16:50 +0200] "GET /confirmdeletion.html?hashes=8042fc9c4910278aa330215aeede403e9c84a42f|bb1f3bc4cd20e514b9867317e463ddb746e57ca5&deleteFiles=false HTTP/2.0" 302 138 "https://qbtvpn.example.com/" 
XX.XX.XX.XX - - [25/Jul/2021:15:16:50 +0200] "GET /authelia/?rd=https://qbtvpn.example.com/confirmdeletion.html?hashes=8042fc9c4910278aa330215aeede403e9c84a42f|bb1f3bc4cd20e514b9867317e463ddb746e57ca5&deleteFiles=false HTTP/2.0" 200 506 "https://qbtvpn.example.com/"
```
Returns 302 and shows Authelia

There always is qBittorrent internal auth so I'm unsure if this has big impact on anything.

**Comment by aptalca** [comment]
Try commenting out these three lines:
https://github.com/linuxserver/docker-swag/blob/master/root/defaults/authelia-server.conf#L13-L15

**Comment by mrskizzex** [comment]
That works but aren't they supposed to be there?

> We don't want to bypass auth for deletion
I was investigated this a bit and you are already doing it, in fact the default file is already exposing underlying api completely and only qbittorent auth is stopping it.  The only thing my addition is doing is returing this box to the user if someone entered 
https://qbtvpn.example.com/confirmdeletion.html?hashes=2383b50f94801bf93d700228f0e13c13884853a1&deleteFiles=false
into their browser. Buttons don't work at all because they require whole page to be loaded properly to work.
image

**Comment by mrskizzex** [comment]
Well my fix doesn't work as well as I thought, this pr can be scrapped. Your fix fixes the root of the issue.
@TheSpad said on discord that those 3 lines were added to mitigate CVE in older versions of authelia, maybe it's worth mentioning in that file? So users can uncomment those out if they have older versions.

**Pull request closed without merging**
