### PR TITLE
Added support for calibre-web subdomain

### PR DESCRIPTION
**Pull request by jwmoss**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by aptalca** [comment]
also needs to make sure the CNAME is for `calibre-web` and not `calibre` (1st line)

**Comment by jwmoss** [comment]
This doesn't work, and it re-directs to https://calibre-web:8083/calibre/login?next=%2Fcalibre%2F

```
# make sure that your dns has a cname set for calibre-web

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name calibre-web.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /login;

        resolver 127.0.0.11 valid=30s;
        set $upstream_calibre calibre-web;
        proxy_pass http://$upstream_calibre:8083;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Script-Name  /calibre; 
    }
}
```

This works great in my environment.

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name calibre-web.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /login;

        resolver 127.0.0.11 valid=30s;
        set $upstream_calibre calibre-web;
        proxy_pass http://$upstream_calibre:8083;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Script-Name /calibre;  # IMPORTANT: path has NO trailing slash
        proxy_set_header X-Forwarded-Host $host;
    }

}
```

**Comment by drizuid** [comment]
you don't need to duplicate proxy_set_header X-Forwarded-Host $host; it is already present in the letsencrypt container. in your two comparisons, the only way X-Forwarded-Host would affect you is if you've modified the default included proxy.conf. 

remember, samples that are adapted into the repo are based on a stock LE container, not one with modifications. 

for reference, here is my working config
```
# make sure that your dns has a cname set for calibre-web

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name calibre-web.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

	location / {
		# enable the next two lines for http auth
		#auth_basic "Restricted";
		#auth_basic_user_file /config/nginx/.htpasswd;

		# enable the next two lines for ldap auth, also customize and enable ldap.conf in the default conf
		#auth_request /auth;
		#error_page 401 =200 /login;

                include /config/nginx/proxy.conf;
		resolver 127.0.0.11 valid=30s;
		set $upstream_calibre_web calibre-web;
		proxy_pass http://$upstream_calibre_web:8083;
		proxy_set_header Host $http_host;
		proxy_set_header X-Scheme $scheme;
		proxy_set_header X-Script-Name /calibre;
	}
}
```

**Comment by jwmoss** [comment]
My proxy.conf was way off, yet I had an updated image, which is a bit bizarre. I'll close this PR for now, as @drizuid provided the correct sample conf. 👍 

Thanks @drizuid and @aptalca.

**Comment by CHBMB** [comment]
>         set $upstream_calibre calibre-web;
>         proxy_pass http://$upstream_calibre:8083;

I wouldn't set upstream as `calibre`.  We have a calibre container already and that will cause issues.  Keep it as `calibre_web`

**Comment by tobbenb** [comment]
The files doesn't get updated when the container gets updated. If you delete them and restart the container you will get the latest file available. There should be a date at the top of the files.

**Comment by jwmoss** [comment]
> > ```
> >     set $upstream_calibre calibre-web;
> >     proxy_pass http://$upstream_calibre:8083;
> > ```
> 
> 
> I wouldn't set upstream as `calibre`.  We have a calibre container already and that will cause issues.  Keep it as `calibre_web`

Makes sense.



> The files doesn't get updated when the container gets updated. If you delete them and restart the container you will get the latest file available. There should be a date at the top of the files.

TIL!

**Pull request closed without merging**
