### PR TITLE
Add resiliosync subdomain proxy-conf for nginx

### PR DESCRIPTION
**Pull request by mcaron1234**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by nemchik** [comment]
Are hyphens valid in nginx variable names such as `$upstream_resilio-sync` ?

**Comment by mcaron1234** [comment]
Not sure about the hyphen in the servername, I don't love resilio-sync.example.com vs resiliosync.example.com, but this way does match the container name.  

I left out the hyphen in the variable name, but added it to the variable value.  My googling suggests it may be possible to have a variable name in nginx with a hyphen but it requires a bit of coding that was over my level.

**Comment by nemchik** [comment]
The `server_name` should be fine with the hyphen, as should the value of the variable. If nginx variables are anything like bash they do not support hyphens in the variable name (because hyphen is a character used for other things).

If that is the case (if nginx does not allow hyphens in variable names) then the variable name will be inconsistent with the container name (value of the variable). My OCD really wants everything to match but it's not my call.

The only other config where this does natch match is nzbhydra, which could easily be renamed to hydra2. Aside from that the unifi-controller config also used a hyphen (just a side note in case this discussion leads to some kind of decision about hyphens).

**Comment by aptalca** [comment]
Hyphen is ok in server name and variable value, but not variable name.

**Comment by mcaron1234** [comment]
Great. This should be all set now, then.

**Comment by aptalca** [comment]
Looks good, but to satisfy my OCD, can you add the hyphen to the filename as well? Then I'll merge

**Comment by aptalca** [comment]
I made the change, this one's ready to go

**Comment by mcaron1234** [comment]
Thanks. I’ve been away for work for a few days.

**Comment by aptalca** [comment]
no worries, I didn't want to make the change myself so I could approve and merge, but now I gotta wait for another team member :-)

**Comment by jkossis** [comment]
Is there any reason for there not to be a corresponding subfolder proxy conf as well?

**Comment by aptalca** [comment]
The reason is either no one bothered to create one, or they tried and couldn't get it to work. Subfolder proxy is very tricky if the upstream app doesn't support a base url

**Pull request merged**
