### PR TITLE
Add Freshrss confs

### PR DESCRIPTION
**Pull request by aptalca**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by BrechtSerckx** [comment]
I am getting an error in the FreshRSS setup: `Blast! Please check that you are not altering your HTTP REFERER.`
Could there be something missing?

**Comment by aptalca** [comment]
Subdomain or subfolder?

**Comment by BrechtSerckx** [comment]
Subdomain

**Comment by aptalca** [comment]
@BrechtSerckx thanks for the heads up. It is now fixed.

**Comment by BrechtSerckx** [comment]
Thanks!

**Pull request merged**
