### PR TITLE
Create overseerr.subdomain.conf.sample

### LINKED ISSUE #251: Config Request Overseerr
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

I´d like to have a working config sample File for [Overseerr](https://github.com/sct/overseerr) as alternative to Ombi.

MR comming in.

### PR DESCRIPTION
**Pull request by Jawbone220**
closes #251

### CODE REVIEW

**Review by aptalca — CHANGES_REQUESTED** [review]
Please add the notice about creating a CNAME for it

**Comment by Jawbone220** [comment]
Added CNAME comment

**Review by aptalca — APPROVED** [review]

**Comment by Sakujakira** [comment]
This Pull Request does use the wrong Port. 5055 must be used since today. 3000 wont work.

**Comment by Jawbone220** [comment]
> 
> 
> This Pull Request does use the wrong Port. 5055 must be used since today. 3000 wont work.

I wanted to wait until the change went live before updating this PR. Will update.

**Pull request merged**
