### PR TITLE
Add .gitignore

### PR DESCRIPTION
**Pull request by nemchik**
This should prevent adding incorrectly named files

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by nemchik** [comment]
This would be to be adjusted for #46 if merged

**Comment by CHBMB** [comment]
I was just about to ask you..... lol

**Comment by nemchik** [comment]
Pretty easy to do regardless which one merges first (if this is approved). This repo shouldn't have much issue with this kind of blanket ignore since it serves a very specific purpose.

Something similar could be accomplished by adjusting line 106 here https://github.com/linuxserver/docker-letsencrypt/blob/master/Dockerfile to only grab the `*.conf.sample` files and the readme.

**Comment by aptalca** [comment]
@nemchik can you modify this to match #46 ?

Thanks

**Comment by nemchik** [comment]
Done

**Pull request merged**
