### PR TITLE
Mailu reverse-proxy (subfolder and subdomain)

### PR DESCRIPTION
**Pull request by vinanrra**
One thing i would like to improve about the reverse proxy it is that is working on domain and subdomains, for example i can use:

- domain.tdl/admin
- domain.tdl/webmail

And if i have any subdomain i can access using:

- suddomain.domain.tdl/admin
- suddomain.domain.tdl/webmail

PD: I saw that adminer reverse proxy have same problem too.

I would like to avoid this "error" to be only accessible via domain.tdl or the subdomain.tdl that i want.

And another improvement i would like to add, but i dont know how, it is to create mailu.subdomain.conf, to be able to access webmail for example via:

- mail.domain.tdl - To access roundcube/rainloop
- mail.domain.tdl/admin - To access control panel

## Improvements:

- [x] Fix folder being accesible via every subdomain (I need help or atleast some info to being able to fix myself)
- [x] Add mailu.subdomain.config (I need help or atleast some info to being able to create myself)

## Important notes:
I will leave here the docker-compose i have used to test this reverse-proxy, i think that this docker-compose should be with the reverse proxy config, because this will usefull for people that want to use the mailu reverse proxy, because i have needed to edit the ports to avoid errors.

```
version: '3.7'
services:     
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: LetsEncrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - URL=DOMAIN.TDL
      - SUBDOMAINS=www,SUBDOMAIN
      - VALIDATION=http
      #- DNSPLUGIN=cloudflare #optional
      #- DUCKDNSTOKEN=<token> #optional
      #- EMAIL=<e-mail> #optional
      - DHLEVEL=2048 #optional
      - ONLY_SUBDOMAINS=false #optional
      #- EXTRA_DOMAINS=<extradomains> #optional
      - STAGING=false #optional
    volumes:
      - ./Web/config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped 
  db:
    image: mysql
    container_name: MySQL
    environment:
      - MYSQL_ROOT_PASSWORD=XXXXXXXXX
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./MySQL/mysql:/var/lib/mysql
    restart: always  
  # External dependencies
  redis:
    image: redis:alpine
    container_name: mailu_redis
    restart: always
    volumes:
      - "./Mailu/redis:/data"
  # Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.7}
    container_name: mailu_front
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - 8080:80
      - 8443:443
      - 25:25
      - 465:465
      - 587:587
      - 110:110
      - 995:995
      - 143:143
      - 993:993
    volumes:
      - "./Mailu/certs:/certs"
      - "./Mailu/overrides/nginx:/overrides"
  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    container_name: mailu_admin
    volumes:
      - "./Mailu/data:/data"
      - "./Mailu/dkim:/dkim"
    depends_on:
      - redis
  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    container_name: mailu_imap
    volumes:
      - "./Mailu/mail:/mail"
      - "./Mailu/overrides:/overrides"
    depends_on:
      - front
  smtp:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    container_name: mailu_smtp
    volumes:
      - "./Mailu/overrides:/overrides"
    depends_on:
      - front
  antispam:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    container_name: mailu_antispam
    volumes:
      - "./Mailu/filter:/var/lib/rspamd"
      - "./Mailu/dkim:/dkim"
      - "./Mailu/overrides/rspamd:/etc/rspamd/override.d"
    depends_on:
      - front
  # Optional services
  antivirus:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    container_name: mailu_antivirus
    volumes:
      - "./Mailu/filter:/data"
  webdav:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    container_name: mailu_webdav
    volumes:
      - "./Mailu/dav:/data"
  fetchmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    container_name: mailu_fetchmail
  # Webmail
  webmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}roundcube:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    container_name: mailu_webmail
    volumes:
      - "./Mailu/webmail:/data"
    depends_on:
      - imap
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
```

### CODE REVIEW

**Comment by vinanrra** [comment]
Change TO-DO to improvements, because the reverse proxy config works, but could be tweaker

**Comment by aptalca** [comment]
for the naked subdomain to access the roundcube you can add this redirect:
```
location / {
    return 301 $scheme://$host/webmail/;
}
```
so any connection at the naked domain will be force redirected to the webmail subfolder.

**Comment by vinanrra** [comment]
Now its working without any erros:

- subfolder
- subdomain

I will create some documentation at mailu's documentation to explain all things need it to do it, if u want to merge with others container, because mailu's auto-configuration it is intended to use it alone.

**Comment by Paullitsch** [comment]
How to use this with an existing swag-docker creating letsencrypt certs?
I tried different .env-files and compose variants but i always get the error:
_Failed to connect to localhost port 80: Connection refused_

could somebody help me, please?

**Pull request merged**
