### PR TITLE
Add Nextcloud HSTS header

### PR DESCRIPTION
**Pull request by bradleyburgess**
Added the recommended HSTS header from Nextcloud admin panel:

image

### CODE REVIEW

**Comment by aptalca** [comment]
Thanks, but it's provided as an option in both proxy.conf in swag, and the default site conf in nextcloud. Both are off by default because hsts is a sledgehammer

**Comment by bradleyburgess** [comment]
@aptalca Thanks! I did check `proxy.conf` but didn't find it in there. I dug around and it's actually in `ssl.conf`. Perhaps a comment in the nextcloud proxy conf pointing to that option?

**Comment by aptalca** [comment]
It's in the nextcloud default site conf with a huge disclaimer: https://github.com/linuxserver/docker-nextcloud/blob/master/root/defaults/default#L17-L26

**Comment by bradleyburgess** [comment]
Gotcha. Thanks.

**Pull request closed without merging**
