### PR TITLE
Create wrapperr.subdomain.conf.sample

### PR DESCRIPTION
**Pull request by MountainGod2**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by MountainGod2** [comment]
Docker hub page to verify ports and name are correct:
https://hub.docker.com/r/aunefyren/wrapperr

**Review by nemchik — CHANGES_REQUESTED** [review]
The proxy templates have been updated with new descriptive comments and auth lines. Please update your PR accordingly.

Ref:
https://github.com/linuxserver/reverse-proxy-confs/blob/master/_template.subdomain.conf.sample
https://github.com/linuxserver/reverse-proxy-confs/blob/master/_template.subfolder.conf.sample

**Comment by MountainGod2** [comment]
Just curious, regarding the version date at the top of the file, is that the template date, or the date the config was created? I updated to today's date, so if that needs to be adjusted, no problem.

**Comment by thespad** [comment]
> Just curious, regarding the version date at the top of the file, is that the template date, or the date the config was created? I updated to today's date, so if that needs to be adjusted, no problem.

It's the date the conf was created or last significantly modified, it's used to notify users when something important has changed and they may need to update their version of the file.

**Review by nemchik — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
