### PR TITLE
add netbox subdomain

### PR DESCRIPTION
**Pull request by ksurl**
add config for netbox subdomain

### CODE REVIEW

**Review by Roxedus — CHANGES_REQUESTED** [review]
-e `ALLOWED_HOST` should be mentioned

**Comment by ksurl** [comment]
added a comment about ALLOWED_HOST.

**Review by nemchik — CHANGES_REQUESTED** [review]
The proxy templates have been updated with new descriptive comments and auth lines. Please update your PR accordingly.

Ref:
https://github.com/linuxserver/reverse-proxy-confs/blob/master/_template.subdomain.conf.sample
https://github.com/linuxserver/reverse-proxy-confs/blob/master/_template.subfolder.conf.sample

**Comment by ksurl** [comment]
added authentik and updated comments

**Review by nemchik — APPROVED** [review]

**Pull request merged**
