### PR TITLE
added osticket.subdomain.conf

### PR DESCRIPTION
**Pull request by zellkou**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by aptalca** [comment]
Thanks for the PR, but why would the port number be changed?

**Comment by zellkou** [comment]
That was a note to myself left in by mistake. I already had the container running before setting up letsencrypt so instead of moving it to the same docker network I just used  $HOSTIP$Port instead of $upstream_osticket:80 in my personal config.

**Comment by aptalca** [comment]
Gotcha, thanks. And one last thing. Please change the subdomain to `osticket` from `help` so it's uniform. Then we'll merge.

**Comment by zellkou** [comment]
No problem, I just went with what was recommend in the osticket documentation for the subdomain name.

**Comment by aptalca** [comment]
I understand. We try to match the subdomain to the app name to prevent any potential collisions between different proxy confs by default. The end users of course can change it to whatever they want when they enable.

Thanks for the changes and the PR.

**Comment by zellkou** [comment]
No problem, I'm just glad I can contribute to the project.

**Pull request merged**
