### PR TITLE
Fix SignalIR, UI wont update

### PR DESCRIPTION
**Pull request by vinanrra**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by vinanrra** [comment]
imagen

**Comment by aptalca** [comment]
Thanks, but this is not necessary. Websockets are automatically handled by the [nginx.conf](https://github.com/linuxserver/docker-swag/blob/master/root/defaults/nginx.conf#L78-L81) and [proxy.conf](https://github.com/linuxserver/docker-swag/blob/master/root/defaults/proxy.conf#L22-L25)

**Comment by vinanrra** [comment]
> 
> 
> Thanks, but this is not necessary. Websockets are automatically handled by the [nginx.conf](https://github.com/linuxserver/docker-swag/blob/master/root/defaults/nginx.conf#L78-L81) and [proxy.conf](https://github.com/linuxserver/docker-swag/blob/master/root/defaults/proxy.conf#L22-L25)

Without that lines i get this error:

Could not connect to SignalR, UI won't update

Should i commit the changes on that file?

**Comment by aptalca** [comment]
Just update your local nginx.conf and proxy.conf as described in the swag changelog: https://github.com/linuxserver/docker-swag#versions

**Pull request closed without merging**
