### PR TITLE
Added fritzbox.subdomain.conf

### PR DESCRIPTION
**Pull request by AndreaPro**
Created a proxy-conf to access the Web Interface of Fritzbox routers

### CODE REVIEW

**Comment by Roxedus** [comment]
> NOTE: We avoid providing samples that publicly expose server management software (ex: syno, qnap, unraid, proxmox, esxi, etc). Pull requests to add samples for this category of applications will not be accepted.

Putting a router on the internet is not a good idea, as it can be dangerous if done wrong.

Closing as this provides great threat if compromised. 

(I know we have exeptions to this rule in the repo already, but ie. unifi, but they have a whole system for authentication, other than just basic_auth. I will reconsider if fritzbox handles authentication better than just with basic_auth)

**Comment by AndreaPro** [comment]
> > NOTE: We avoid providing samples that publicly expose server management software (ex: syno, qnap, unraid, proxmox, esxi, etc). Pull requests to add samples for this category of applications will not be accepted.
> 
> Putting a router on the internet is not a good idea, as it can be dangerous if done wrong.
> 
> Closing as this provides great threat if compromised.
> 
> (I know we have exeptions to this rule in the repo already, but ie. unifi, but they have a whole system for authentication, other than just basic_auth. I will reconsider if fritzbox handles authentication better than just with basic_auth)

Inside the router is possible to enable access from the internet, by reverse proxying it there is the advantage of having a valid certificate for https and on my local configuration I've restricted access to the web interface only if it comes from the local network so I can use it behind a VPN. I have two other files one for OpenMediaVault and one for Cockpit, I can submit them or even these are too dangerous?

**Comment by TheSpad** [comment]
> 
> 
> > > NOTE: We avoid providing samples that publicly expose server management software (ex: syno, qnap, unraid, proxmox, esxi, etc). Pull requests to add samples for this category of applications will not be accepted.
> > 
> > 
> > Putting a router on the internet is not a good idea, as it can be dangerous if done wrong.
> > Closing as this provides great threat if compromised.
> > (I know we have exeptions to this rule in the repo already, but ie. unifi, but they have a whole system for authentication, other than just basic_auth. I will reconsider if fritzbox handles authentication better than just with basic_auth)
> 
> Inside the router is possible to enable access from the internet, by reverse proxying it there is the advantage of having a valid certificate for https and on my local configuration I've restricted access to the web interface only if it comes from the local network so I can use it behind a VPN. I have two other files one for OpenMediaVault and one for Cockpit, I can submit them or even these are too dangerous?

They would also be rejected.

If you know what you're doing you can obviously setup whatever confs you want to, but we don't want to publish any sample confs that could lead to people accidentally exposing their infrastructure management interfaces to the internet.

**Comment by Roxedus** [comment]
Those falls under the same category. 

> __*I've*__ restricted access to the web interface only if it comes from the local network

Most people will just enable it, and be unprotected. Our stance here is; if you know how to make it safe, you know how to create the proxy

**Pull request closed without merging**
