### PR TITLE
Add authentik config lines and adjust comments

### PR DESCRIPTION
**Pull request by nemchik**
Replaces https://github.com/linuxserver/reverse-proxy-confs/pull/519
Requires https://github.com/linuxserver/docker-swag/pull/331

### CODE REVIEW

**Comment by roib20** [comment]
Is this planned to get merged soon? Should we include the authentik config lines in new Pull Requests?

**Comment by nemchik** [comment]
We need the configs here https://github.com/linuxserver/docker-swag/blob/cba7e6703c666caba85443e420b2c209a62bf200/root/defaults/nginx/authentik-location.conf.sample and here https://github.com/linuxserver/docker-swag/blob/cba7e6703c666caba85443e420b2c209a62bf200/root/defaults/nginx/authentik-server.conf.sample tested.

If they work then they will be merged into https://github.com/linuxserver/docker-swag/pull/331 
If they do not work then https://github.com/linuxserver/docker-swag/pull/331 will likely be merged as-is, and this PR would be merged either way.

**Review by drizuid — APPROVED** [review]
lgtm, glad you did this, because i sure as hell wasn't :D

**Comment by roib20** [comment]
This seems to also replace #449. Therefore in my opinion that issue can be closed.

Anyone wanting to update their PR for Authentik should base their changes on the samples from #521 here.

**Pull request merged**
