### PR TITLE
Update organizr.subfolder.conf.sample

### PR DESCRIPTION
**Pull request by 19wolf**
Wording might need some tweaking but trying to make it clear there are other options.

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by nemchik** [comment]
I believe doing this also requires some reconfiguring in the nginx config of the Organizr container.

**Comment by 19wolf** [comment]
I don't think so. There's no place within organizr that I saw to "specify subdirectory" like you need to do with ex. sonarr. 

I'm not sure if this file would then need to point to port 9983 [as specified](https://github.com/linuxserver/docker-organizr)? You would definitely need to change the port if you need to change the upstream app section. I have my letsencrypt and organizr in different compose files so they're by default on different networks so I needed to do that, which is specified somewhere?

**Comment by nemchik** [comment]
Our Organizr image is still v1 which the dev no longer updates. They maintain a v2 image. Inside the config is an nginx config that has a `/` location. You would need to adjust that in order to run Organizr on a subfolder.

**Comment by nemchik** [comment]
Closing this. If you need help getting this type of config working please visit our discord or the Organizr discord.

**Pull request closed without merging**
