### PR TITLE
filebot.subfolder.conf.sample and picard.subfolder.conf.sample

### PR DESCRIPTION
**Pull request by D4rkSl4ve**
Add working `subfolder.conf` for Filebot and Picard

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Review by D4rkSl4ve — COMMENTED** [review]
Everything seems properly tagged

**Comment by Roxedus** [comment]
You are missing the date line, the one that is in all the other samples

**Review by D4rkSl4ve — COMMENTED** [review]
Added ## Version 2021/01/16

**Review by D4rkSl4ve — COMMENTED** [review]
Added ## Version 2021/01/16

**Review by Roxedus — APPROVED** [review]

**Review by D4rkSl4ve — COMMENTED** [review]
.

**Pull request merged**
