### PR TITLE
Updates for Nextcloud security checks

### PR DESCRIPTION
**Pull request by hollanbm**
Identical changes as #367 but made in the subdomain conf

resolves warnings from Nextcloud security check

### CODE REVIEW

**Comment by hollanbm** [comment]
Should I update the date in the comment at the top, or is that done automatically on build?

**Comment by Roxedus** [comment]
You need to update it

**Comment by hollanbm** [comment]
> You need to update it

done. thanks

**Comment by aptalca** [comment]
This shouldn't be needed as nextcloud's site conf already handles the redirects

**Comment by hollanbm** [comment]
> This shouldn't be needed as nextcloud's site conf already handles the redirects

Am I missing something?

These config options were required for me to pass the security checks in the NextCloud app Admin Overview section

Without
image
  
Without
image

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-nextcloud/blob/master/root/defaults/default#L88-L101

**Comment by hollanbm** [comment]
> https://github.com/linuxserver/docker-nextcloud/blob/master/root/defaults/default#L88-L101

Thank you. This installation is a few years old. I just keep upgrading in place.I don't see a date at the top of my current `site-conf` in the nextcloud container. But mine is definitely dated.

I'll compare against the other files in the default folder and see what I need to update

**Comment by aptalca** [comment]
If you haven't customized it, just delete it and restart the container. It will generate the latest one in there.

**Comment by hollanbm** [comment]
> If you haven't customized it, just delete it and restart the container. It will generate the latest one in there.

I hadn't, I'll do that. Thanks for the help

**Pull request closed without merging**
