### PR TITLE
Handle Nginx http auth + grafana auth separately

### PR DESCRIPTION
**Pull request by draco2003**
Went down a rabbit hole because I had my "admin" type subdirectory protected by http auth, but the individual apps have their own user auth. The passed authorization header was causing problems with Grafana.

### CODE REVIEW

**Review by Roxedus — CHANGES_REQUESTED** [review]
Please update the date at the top

**Comment by Roxedus** [comment]
Would be awesome if you did the same to the subdomain

**Comment by draco2003** [comment]
This passes the build regex:
## Version 2021/01/28
this doesn't
## Version 2021/01/29

Should have posted this yesterday or Monday it looks like ;)

**Comment by aptalca** [comment]
lol, I'll blame @nemchik as I have no energy to try and dissect that massive regex 😅

**Comment by nemchik** [comment]
The other pr wasn't meant to close this, just fix the gha date issue.

**Comment by nemchik** [comment]
@draco2003 please merge from master to get the updated gha and your checks should pass.

**Review by Roxedus — APPROVED** [review]

**Pull request merged**
