### PR TITLE
ttrss subdomain

### PR DESCRIPTION
**Pull request by CHBMB**
I'm not sure if subfolder is actually possible, and I don't use ttrss myself, but this may be helpful to some.

### CODE REVIEW

**Comment by nemchik** [comment]
Does the hyphen conversation from https://github.com/linuxserver/reverse-proxy-confs/pull/22 apply here?

**Comment by aptalca** [comment]
not a hyphen issue, but it seems we used the wrong container name. I'll PR a fix

**Comment by ryester27** [comment]
Serving from a subfolder should be possible, but I haven't had much luck passing the sanity checks with my own attempts at writing a nginx config. I'll give it another try now that there's a confirmed working config that I can look at

**Comment by nemchik** [comment]
I've got a mostly working subfolder conf, but when you login it redirects you to the domain without the subfolder. The login does work, you just have to go back to the subfolder URL manually.

**Comment by ryester27** [comment]
> I've got a mostly working subfolder conf, but when you login it redirects you to the domain without the subfolder. The login does work, you just have to go back to the subfolder URL manually.

That's about been my experience as well. There's also some other oddities like the "close this window" button not working on some windows, and unsubscribing from a feed throws an exemption.

I'd like to see if I can get this working without any config changes to the linuxserver/tt-rss container, but it's very much possible that tt-rss does need to run from within a subfolder at the tt-rss container's webserver root

**Comment by nemchik** [comment]
The config.php explicitly lists `http://example.org/tt-rss/` for `SELF_URL_PATH` so I'm assuming they at least have accounted for the idea of subfolder proxies in some way, but I still get the odd behavior. Here's what I've come up with https://github.com/nemchik/reverse-proxy-confs/blob/ce084952ea6431c66dc8c239066cc9a44234229d/tt-rss.subfolder.conf.sample

**Comment by ryester27** [comment]
> The config.php explicitly lists `http://example.org/tt-rss/` for `SELF_URL_PATH` so I'm assuming they at least have accounted for the idea of subfolder proxies in some way, but I still get the odd behavior. Here's what I've come up with https://github.com/nemchik/reverse-proxy-confs/blob/ce084952ea6431c66dc8c239066cc9a44234229d/tt-rss.subfolder.conf.sample

The fact that's there's a sanity check at all for the SELF_URL_PATH value leads me to believe that if you want tt-rss to be served from a subfolder, that it must reside in a subfolder at the document root. Rewriting URI requests only goes so far.

Anyways, we should probably create a separate issue to continue discussion.

**Pull request merged**
